version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "lambda-sam"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-12hmsg9oqoqze"
s3_prefix = "lambda-sam"
region = "us-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"

