AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  lambda-sam

  Sample SAM Template for lambda-sam

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 60

Resources:
  MusaicGeneratorFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: musaic/
      Handler: lambda_function.lambda_handler
      Runtime: python2.7
      MemorySize: 1792
      Policies:
        - AmazonS3FullAccess
  MusaicGeneratorStepFunction:
    Type: AWS::StepFunctions::StateMachine
    Properties:
      RoleArn: !GetAtt MusaicGeneratorStepFunctionIamRole.Arn
      StateMachineName: MusaicGenerator-StateMachine
      DefinitionString: !Sub |-
        {
          "Comment": "Step Function to asynchronously execute musaic lambda function",
          "StartAt": "Generate",
          "States": {
            "Generate": {
              "Type": "Task",
              "Resource": "${MusaicGeneratorFunction.Arn}",
              "End": true
            }
          }
        }
  MusaicGeneratorStepFunctionIamRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - states.amazonaws.com
            Action: 
                - 'sts:AssumeRole'
      Path: /
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/CloudWatchFullAccess
        - arn:aws:iam::aws:policy/service-role/AWSLambdaRole

Outputs:
  MusaicGeneratorFunction:
    Description: "Musaic Generator Lambda Function ARN"
    Value: !GetAtt MusaicGeneratorFunction.Arn
  MusaicGeneratorFunctionIamRole:
    Description: "Implicit IAM Role created for Musaic Generator function"
    Value: !GetAtt MusaicGeneratorFunction.Arn
