AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  lambda-sam

  Sample SAM Template for lambda-sam

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 60

Resources:
  MusaicGeneratorFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: musaic/
      Handler: lambda_function.lambda_handler
      Runtime: python2.7
      MemorySize: 1024
      Policies:
        - AmazonS3FullAccess

Outputs:
  MusaicGeneratorFunction:
    Description: "Musaic Generator Lambda Function ARN"
    Value: !GetAtt MusaicGeneratorFunction.Arn
  MusaicGeneratorFunctionIamRole:
    Description: "Implicit IAM Role created for Musaic Generator function"
    Value: !GetAtt MusaicGeneratorFunction.Arn
